name: expense_tracker
description: A smart personal finance & expense tracker app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.68.0

  intl: ^0.18.1
  equatable: ^2.0.5
  path_provider: ^2.0.15
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icon_app.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_app.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F8FAFC"
  color_dark: "#0F172A"
  image: lib/assets/icon_app.jpg
  android: true
  ios: true
  web: false
  android_12:
    color: "#F8FAFC"
    color_dark: "#0F172A"
    image: lib/assets/icon_app.jpg
  fullscreen: true